# docker build -t ec2-deploy.base -f Dockerfile.base ~/projects/deploy/ec2-deploy
FROM        python:3.6.4

RUN         apt-get -y update
RUN         apt-get -y dist-upgrade

COPY        . /srv/project

WORKDIR     /srv/project
RUN         pip install -r requirements.txt